---
- name: This playbook creates a file or dir
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: creating a file
      file:
        path: /home/ansadmin/demodir
        state: directory

